/**
 * This file is auto-generated by the module import system.
 * Do not edit manually.
 * 
 * When modules are imported, routes are automatically added here.
 */

import type { RouteObject } from 'react-router-dom';

// Export empty array by default - will be populated by module import system
export const installedRoutes: RouteObject[] = [];

