import { createBrowserRouter } from 'react-router-dom';
import RootLayout from '../layouts/RootLayout';
import MainLayout from '../layouts/MainLayout';
import { ProtectedRoute } from '../app/components/auth/ProtectedRoute';
import { PlansProvider } from '../app/contexts/PlansContext';
import { InspectionRoundsProvider } from '../contexts/InspectionRoundsContext';
import Error404 from '../pages/system/Error404';

// Import route groups
import { authRoutes } from './authRoutes';
import { mainRoutes } from './mainRoutes';
import { plansRoutes } from './plansRoutes';
import { tasksRoutes } from './tasksRoutes';
import { registryRoutes } from './registryRoutes';
import { leadRiskRoutes } from './leadRiskRoutes';
import { accountRoutes } from './accountRoutes';
import { systemRoutes } from './systemRoutes';

// Import installed module routes (auto-generated by module import system)
import { installedRoutes } from '../imports/installedModules';

// Wrapper component for protected routes
function ProtectedLayout() {
  return (
    <PlansProvider>
      <InspectionRoundsProvider>
        <ProtectedRoute>
          <MainLayout />
        </ProtectedRoute>
      </InspectionRoundsProvider>
    </PlansProvider>
  );
}

export const router = createBrowserRouter([
  {
    element: <RootLayout />,
    children: [
      // Auth routes (no layout)
      ...authRoutes,

      // Main app routes (with layout + protected)
      {
        path: '/',
        element: <ProtectedLayout />,
        children: [
          // Main routes
          ...mainRoutes,
          // Plans routes
          ...plansRoutes,
          // Tasks routes
          ...tasksRoutes,
          // Registry routes
          ...registryRoutes,
          // Lead & Risk routes
          ...leadRiskRoutes,
          // Account routes
          ...accountRoutes,
          // System routes
          ...systemRoutes,
          // Installed module routes
          ...installedRoutes,
        ],
      },
      // Catch all - redirect to 404
      {
        path: '*',
        element: <Error404 />,
      },
    ],
  },
]);